//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPieceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Price_Id { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> Price1 { get; set; }
    }
}
