//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPieceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Request_Id { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<decimal> Lantitude { get; set; }
        public Nullable<decimal> Longtitude { get; set; }
        public string userId { get; set; }
        public Nullable<int> Subscriper_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Subscriper Subscriper { get; set; }
    }
}
