//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPieceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscriper()
        {
            this.Comments = new HashSet<Comment>();
            this.Requests = new HashSet<Request>();
        }
    
        public int Subscriper_Id { get; set; }
        public string userId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Subscriper_Photo { get; set; }
        public Nullable<int> Service_Id { get; set; }
        public string Location { get; set; }
        public string Service_Description { get; set; }
        public Nullable<System.TimeSpan> Beg_Time { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Shown { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        public virtual Service Service { get; set; }
    }
}
